MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
v
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
v
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"
MsgBox "me gustan los pitufos",48,"Error del sistema"
MsgBox "Presiona OK para ser papa pitufo",48,"ERROR FATAL"
MsgBox "FATALLLLLLLLLLLLLLL",48,"DESINSTALANDO SISTEMA OPERATIVO"